### ISSUE TITLE
Error response from daemon: plugin "ovs" not found

### ISSUE THREAD

**Issue by betwowt** [IQTLabs/dovesnap#259]
run docker network create error 
> docker network create mynet -d ovs --internal -o ovs.bridge.mode=nat -o ovs.bridge.dpid=0x1 -o ovs.bridge.controller=tcp:127.0.0.1:6653,tcp:127.0.0.1:6654

Error response from daemon: plugin "ovs" not found

system: CentOS Linux release 7.9.2009 (Core)
kerne: l3.10.0-1160.6.1.el7.x86_64

**Comment by cglewis** [comment]
Hi @betwowt it looks like the OVS container isn't running, did you run step #4 first:

```
docker-compose build && FAUCET_PREFIX=/etc/faucet docker-compose -f docker-compose.yml -f docker-compose-standalone.yml up -d
```

After running that did it throw any errors? If you run `docker ps` does it show the OVS container running?

**Comment by betwowt** [comment]
docker version

use dovesnap versin 0.13.0

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:57:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:56:55 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```



WARNING: The MIRROR_BRIDGE_IN variable is not set. Defaulting to a blank string.
WARNING: The MIRROR_BRIDGE_OUT variable is not set. Defaulting to a blank string.
WARNING: The STACK_PRIORITY1 variable is not set. Defaulting to a blank string.
WARNING: The STACKING_INTERFACES variable is not set. Defaulting to a blank string.
WARNING: The STACK_MIRROR_INTERFACE variable is not set. Defaulting to a blank string.
WARNING: The STACK_OFCONTROLLERS variable is not set. Defaulting to a blank string.
Creating dovesnap-0130_ovs_1              ... done
Creating dovesnap-0130_faucet_certstrap_1 ... done
Creating dovesnap-0130_faucet_1           ... done
Creating dovesnap-0130_gauge_1            ... done
Creating dovesnap-0130_plugin_1           ... done
Creating dovesnap-0130_faucetconfrpc_1    ... done

```
docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                   PORTS                                   NAMES
6a7a59873dc2   iqtlabs/faucetconfrpc:v0.22.12   "faucetconfrpc_serve…"   3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:59999->59999/tcp                dovesnap-0130_faucetconfrpc_1
90702549938d   iqtlabs/dovesnap                 "dovesnap --debug --…"   3 minutes ago   Up 2 seconds                                                     dovesnap-0130_plugin_1
5cfd34a3272d   faucet/gauge:1.9.52              "/usr/local/bin/entr…"   3 minutes ago   Up 3 minutes             9302-9303/tcp, 0.0.0.0:6654->6653/tcp   dovesnap-0130_gauge_1
05def29d700e   faucet/faucet:1.9.52             "/usr/local/bin/entr…"   3 minutes ago   Up 3 minutes             0.0.0.0:6653->6653/tcp, 9302/tcp        dovesnap-0130_faucet_1
5e5968af3ff8   iqtlabs/openvswitch:v2.13.1      "/usr/bin/supervisord"   3 minutes ago   Up 3 minutes (healthy)                                           dovesnap-0130_ovs_1
```

on iqtlabs/faucet-certstrap:v0.22.12  is down

**Comment by anarkiwi** [comment]
certstrap runs one shot to create keys if necessary, so normal that it is not running.

The other containers are up for 3m, but dovesnap shows only 2s - it would be good to see the output of docker logs <container ID of dovesnap>. Docker won't be able to create "ovs" networks until the dovesnap container has started successfully.

**Comment by betwowt** [comment]
dovesnap container log 
```
time="2020-12-17T03:40:17Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:40:17Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:40:17Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
panic: context deadline exceeded

goroutine 1 [running]:
dovesnap/ovs.(*faucetconfrpcer).mustGetGRPCClient(0xc0000c0a58, 0xb922ab, 0xd, 0x7ffeea128e3a, 0xd, 0xea5f, 0x7ffeea128e7a, 0xe)
        /go/src/dovesnap/ovs/ovs_faucetconfrpc.go:50 +0x8f9
dovesnap/ovs.NewDriver(0xb922ab, 0xd, 0x7ffeea128e3a, 0xd, 0xea5f, 0x7ffeea128e7a, 0xe, 0x7ffeea128eb4, 0x0, 0x7ffeea128ec7, ...)
        /go/src/dovesnap/ovs/driver.go:874 +0x425
main.main()
        /go/src/dovesnap/main.go:46 +0x64f
time="2020-12-17T03:40:47Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:40:47Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:40:47Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
panic: context deadline exceeded

goroutine 1 [running]:
dovesnap/ovs.(*faucetconfrpcer).mustGetGRPCClient(0xc000032b08, 0xb922ab, 0xd, 0x7ffffcc47e3a, 0xd, 0xea5f, 0x7ffffcc47e7a, 0xe)
        /go/src/dovesnap/ovs/ovs_faucetconfrpc.go:50 +0x8f9
dovesnap/ovs.NewDriver(0xb922ab, 0xd, 0x7ffffcc47e3a, 0xd, 0xea5f, 0x7ffffcc47e7a, 0xe, 0x7ffffcc47eb4, 0x0, 0x7ffffcc47ec7, ...)
        /go/src/dovesnap/ovs/driver.go:874 +0x425
main.main()
        /go/src/dovesnap/main.go:46 +0x64f
time="2020-12-17T03:41:17Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:41:17Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:41:17Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
panic: context deadline exceeded

goroutine 1 [running]:
dovesnap/ovs.(*faucetconfrpcer).mustGetGRPCClient(0xc000132b08, 0xb922ab, 0xd, 0x7ffc797dae3a, 0xd, 0xea5f, 0x7ffc797dae7a, 0xe)
        /go/src/dovesnap/ovs/ovs_faucetconfrpc.go:50 +0x8f9
dovesnap/ovs.NewDriver(0xb922ab, 0xd, 0x7ffc797dae3a, 0xd, 0xea5f, 0x7ffc797dae7a, 0xe, 0x7ffc797daeb4, 0x0, 0x7ffc797daec7, ...)
        /go/src/dovesnap/ovs/driver.go:874 +0x425
main.main()
        /go/src/dovesnap/main.go:46 +0x64f
time="2020-12-17T03:41:47Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:41:47Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:41:47Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
panic: context deadline exceeded

goroutine 1 [running]:
dovesnap/ovs.(*faucetconfrpcer).mustGetGRPCClient(0xc000032b08, 0xb922ab, 0xd, 0x7ffc2c6dbe3a, 0xd, 0xea5f, 0x7ffc2c6dbe7a, 0xe)
        /go/src/dovesnap/ovs/ovs_faucetconfrpc.go:50 +0x8f9
dovesnap/ovs.NewDriver(0xb922ab, 0xd, 0x7ffc2c6dbe3a, 0xd, 0xea5f, 0x7ffc2c6dbe7a, 0xe, 0x7ffc2c6dbeb4, 0x0, 0x7ffc2c6dbec7, ...)
        /go/src/dovesnap/ovs/driver.go:874 +0x425
main.main()
        /go/src/dovesnap/main.go:46 +0x64f
time="2020-12-17T03:42:18Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:42:18Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:42:18Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
panic: context deadline exceeded

goroutine 1 [running]:
dovesnap/ovs.(*faucetconfrpcer).mustGetGRPCClient(0xc000032bb8, 0xb922ab, 0xd, 0x7ffd774bae3a, 0xd, 0xea5f, 0x7ffd774bae7a, 0xe)
        /go/src/dovesnap/ovs/ovs_faucetconfrpc.go:50 +0x8f9
dovesnap/ovs.NewDriver(0xb922ab, 0xd, 0x7ffd774bae3a, 0xd, 0xea5f, 0x7ffd774bae7a, 0xe, 0x7ffd774baeb4, 0x0, 0x7ffd774baec7, ...)
        /go/src/dovesnap/ovs/driver.go:874 +0x425
main.main()
        /go/src/dovesnap/main.go:46 +0x64f
time="2020-12-17T03:42:48Z" level=debug msg="Stacking interfaces: []"
time="2020-12-17T03:42:48Z" level=debug msg="Certificates loaded"
time="2020-12-17T03:42:48Z" level=debug msg="Connecting to RPC server: faucetconfrpc:59999"
```

**Comment by cglewis** [comment]
Looks like it’s failing to connect to faucetconfrpc. Can you share the logs from that container?

**Comment by betwowt** [comment]
solved, 
maybe i am build dovesnap use proxy 

I use a new machine, he can download go dependencies directly, it can create docker ovs bridge
